### PR TITLE
AL-368: Full E2E local biometrics auth RPi<>Altria BE

### PR DESCRIPTION
**Pull request by bryanv-verytech**
This PR ties the the final piece HW demo together. It adds patching the biometric auth state change to the device object in the BE. This is working as expected between Altria device<>GW<>BE, I will hold off merging this until the FE piece is in place.

I also made some changes to help with BLE connection stability (Altria device<>GW)

### CODE REVIEW

**Review by azkane — APPROVED** [review]
Hard to speak for the HW integration part, but the rest integration lgtm.

FE part should be merged now too.

**Comment by bryanv-verytech** [comment]
> Hard to speak for the HW integration part, but the rest integration lgtm.
> 
> FE part should be merged now too.

The UI is working as expected! One Q though: We want the button to be disabled? I was envisioning that would function the same and also update the device state in the BE?
CC: @garrettmichaelgeorge

**Comment by azkane** [comment]
Wouldn't you have to be polling the device endpoint too for that to work?

**Comment by bryanv-verytech** [comment]
> > One Q though: We want the button to be disabled? I was envisioning that would function the same and also update the device state in the BE?
> 
> We can work this out on [Slack](https://verytechnology.slack.com/archives/C03R4455UAW/p1693434349351599?thread_ts=1693247199.267639&cid=C03R4455UAW). For now, this question doesn't affect whether this PR gets merged, does it?

Yeah, we'll resolve this on slack. And yes, it does **_not_** affect this PR/change

**Pull request merged**
